export const pokedex = [
    {
        "DEX": 1,
        "POKEMON": "Bulbasaur",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Overgrow",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Chlorophyll",
        "EG 1": "Monster",
        "EG 2": "Grass",
        "HEALTH POINTS": 45,
        "ATTACK": 49,
        "DEFENSE": 49,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 65,
        "SPEED": 45,
        "TOTAL": 318,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 2,
        "POKEMON": "Ivysaur",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Overgrow",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Chlorophyll",
        "EG 1": "Monster",
        "EG 2": "Grass",
        "HEALTH POINTS": 60,
        "ATTACK": 62,
        "DEFENSE": 63,
        "SPECIAL ATTACK": 80,
        "SPECIAL DEFENSE": 80,
        "SPEED": 60,
        "TOTAL": 405,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 3,
        "POKEMON": "Venusaur",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Overgrow",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Chlorophyll",
        "EG 1": "Monster",
        "EG 2": "Grass",
        "HEALTH POINTS": 80,
        "ATTACK": 82,
        "DEFENSE": 83,
        "SPECIAL ATTACK": 100,
        "SPECIAL DEFENSE": 100,
        "SPEED": 80,
        "TOTAL": 525,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 4,
        "POKEMON": "Charmander",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Blaze",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Solar Power",
        "EG 1": "Monster",
        "EG 2": "Dragon",
        "HEALTH POINTS": 39,
        "ATTACK": 52,
        "DEFENSE": 43,
        "SPECIAL ATTACK": 60,
        "SPECIAL DEFENSE": 50,
        "SPEED": 65,
        "TOTAL": 309,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 5,
        "POKEMON": "Charmeleon",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Blaze",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Solar Power",
        "EG 1": "Monster",
        "EG 2": "Dragon",
        "HEALTH POINTS": 58,
        "ATTACK": 64,
        "DEFENSE": 58,
        "SPECIAL ATTACK": 80,
        "SPECIAL DEFENSE": 65,
        "SPEED": 80,
        "TOTAL": 405,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 6,
        "POKEMON": "Charizard",
        "TYPE 1": "Fire",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Blaze",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Solar Power",
        "EG 1": "Monster",
        "EG 2": "Dragon",
        "HEALTH POINTS": 78,
        "ATTACK": 84,
        "DEFENSE": 78,
        "SPECIAL ATTACK": 109,
        "SPECIAL DEFENSE": 85,
        "SPEED": 100,
        "TOTAL": 534,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 7,
        "POKEMON": "Squirtle",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Torrent",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Rain Dish",
        "EG 1": "Monster",
        "EG 2": "Water 1",
        "HEALTH POINTS": 44,
        "ATTACK": 48,
        "DEFENSE": 65,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 64,
        "SPEED": 43,
        "TOTAL": 314,
        "HATCH STEPS": 2560
    },
    {
        "DEX": 8,
        "POKEMON": "Wartortle",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Torrent",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Rain Dish",
        "EG 1": "Monster",
        "EG 2": "Water 1",
        "HEALTH POINTS": 59,
        "ATTACK": 63,
        "DEFENSE": 80,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 80,
        "SPEED": 58,
        "TOTAL": 405,
        "HATCH STEPS": 2560
    },
    {
        "DEX": 9,
        "POKEMON": "Blastoise",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Torrent",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Rain Dish",
        "EG 1": "Monster",
        "EG 2": "Water 1",
        "HEALTH POINTS": 79,
        "ATTACK": 83,
        "DEFENSE": 100,
        "SPECIAL ATTACK": 85,
        "SPECIAL DEFENSE": 105,
        "SPEED": 78,
        "TOTAL": 530,
        "HATCH STEPS": 2560
    },
    {
        "DEX": 10,
        "POKEMON": "Caterpie",
        "TYPE 1": "Bug",
        "TYPE 2": "",
        "ABILITIES 1": "Shield Dust",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Run Away",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 45,
        "ATTACK": 30,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 20,
        "SPECIAL DEFENSE": 20,
        "SPEED": 45,
        "TOTAL": 195,
        "HATCH STEPS": 2560
    },
    {
        "DEX": 11,
        "POKEMON": "Metapod",
        "TYPE 1": "Bug",
        "TYPE 2": "",
        "ABILITIES 1": "Shed Skin",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 50,
        "ATTACK": 20,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 25,
        "SPECIAL DEFENSE": 25,
        "SPEED": 30,
        "TOTAL": 205,
        "HATCH STEPS": 2560
    },
    {
        "DEX": 12,
        "POKEMON": "Butterfree",
        "TYPE 1": "Bug",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Compoundeyes",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Tinted Lens",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 60,
        "ATTACK": 45,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 90,
        "SPECIAL DEFENSE": 80,
        "SPEED": 70,
        "TOTAL": 395,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 13,
        "POKEMON": "Weedle",
        "TYPE 1": "Bug",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Shield Dust",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Run Away",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 35,
        "DEFENSE": 30,
        "SPECIAL ATTACK": 20,
        "SPECIAL DEFENSE": 20,
        "SPEED": 50,
        "TOTAL": 195,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 14,
        "POKEMON": "Kakuna",
        "TYPE 1": "Bug",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Shed Skin",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 45,
        "ATTACK": 25,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 25,
        "SPECIAL DEFENSE": 25,
        "SPEED": 35,
        "TOTAL": 205,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 15,
        "POKEMON": "Beedrill",
        "TYPE 1": "Bug",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Swarm",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Sniper",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 90,
        "DEFENSE": 40,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 80,
        "SPEED": 75,
        "TOTAL": 395,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 16,
        "POKEMON": "Pidgey",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Keen Eye",
        "ABILITIES 2": "Tangled Feet",
        "HIDDEN ABILITY": "Big Pecks",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 45,
        "DEFENSE": 40,
        "SPECIAL ATTACK": 35,
        "SPECIAL DEFENSE": 35,
        "SPEED": 56,
        "TOTAL": 251,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 17,
        "POKEMON": "Pidgeotto",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Keen Eye",
        "ABILITIES 2": "Tangled Feet",
        "HIDDEN ABILITY": "Big Pecks",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 63,
        "ATTACK": 60,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 50,
        "SPEED": 71,
        "TOTAL": 349,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 18,
        "POKEMON": "Pidgeot",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Keen Eye",
        "ABILITIES 2": "Tangled Feet",
        "HIDDEN ABILITY": "Big Pecks",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 83,
        "ATTACK": 80,
        "DEFENSE": 75,
        "SPECIAL ATTACK": 70,
        "SPECIAL DEFENSE": 70,
        "SPEED": 101,
        "TOTAL": 479,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 19,
        "POKEMON": "Rattata",
        "TYPE 1": "Normal",
        "TYPE 2": "",
        "ABILITIES 1": "Run Away",
        "ABILITIES 2": "Guts",
        "HIDDEN ABILITY": "Hustle",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 30,
        "ATTACK": 56,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 25,
        "SPECIAL DEFENSE": 35,
        "SPEED": 72,
        "TOTAL": 253,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 20,
        "POKEMON": "Raticate",
        "TYPE 1": "Normal",
        "TYPE 2": "",
        "ABILITIES 1": "Run Away",
        "ABILITIES 2": "Guts",
        "HIDDEN ABILITY": "Hustle",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 55,
        "ATTACK": 81,
        "DEFENSE": 60,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 70,
        "SPEED": 97,
        "TOTAL": 413,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 21,
        "POKEMON": "Spearow",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Keen Eye",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Sniper",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 60,
        "DEFENSE": 30,
        "SPECIAL ATTACK": 31,
        "SPECIAL DEFENSE": 31,
        "SPEED": 70,
        "TOTAL": 262,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 22,
        "POKEMON": "Fearow",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Keen Eye",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Sniper",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 90,
        "DEFENSE": 65,
        "SPECIAL ATTACK": 61,
        "SPECIAL DEFENSE": 61,
        "SPEED": 100,
        "TOTAL": 442,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 23,
        "POKEMON": "Ekans",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Intimidate",
        "ABILITIES 2": "Shed Skin",
        "HIDDEN ABILITY": "Unnerve",
        "EG 1": "Field",
        "EG 2": "Dragon",
        "HEALTH POINTS": 35,
        "ATTACK": 60,
        "DEFENSE": 44,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 54,
        "SPEED": 55,
        "TOTAL": 288,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 24,
        "POKEMON": "Arbok",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Intimidate",
        "ABILITIES 2": "Shed Skin",
        "HIDDEN ABILITY": "Unnerve",
        "EG 1": "Field",
        "EG 2": "Dragon",
        "HEALTH POINTS": 60,
        "ATTACK": 85,
        "DEFENSE": 69,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 79,
        "SPEED": 80,
        "TOTAL": 438,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 25,
        "POKEMON": "Pikachu",
        "TYPE 1": "Electric",
        "TYPE 2": "",
        "ABILITIES 1": "Static",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Lightningrod",
        "EG 1": "Field",
        "EG 2": "Fairy",
        "HEALTH POINTS": 35,
        "ATTACK": 55,
        "DEFENSE": 40,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 50,
        "SPEED": 90,
        "TOTAL": 320,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 26,
        "POKEMON": "Raichu",
        "TYPE 1": "Electric",
        "TYPE 2": "",
        "ABILITIES 1": "Static",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Lightningrod",
        "EG 1": "Field",
        "EG 2": "Fairy",
        "HEALTH POINTS": 60,
        "ATTACK": 90,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 90,
        "SPECIAL DEFENSE": 80,
        "SPEED": 110,
        "TOTAL": 485,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 27,
        "POKEMON": "Sandshrew",
        "TYPE 1": "Ground",
        "TYPE 2": "",
        "ABILITIES 1": "Sand Veil",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Sand Rush",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 50,
        "ATTACK": 75,
        "DEFENSE": 85,
        "SPECIAL ATTACK": 20,
        "SPECIAL DEFENSE": 30,
        "SPEED": 40,
        "TOTAL": 300,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 28,
        "POKEMON": "Sandslash",
        "TYPE 1": "Ground",
        "TYPE 2": "",
        "ABILITIES 1": "Sand Veil",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Sand Rush",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 75,
        "ATTACK": 100,
        "DEFENSE": 110,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 55,
        "SPEED": 65,
        "TOTAL": 450,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 29,
        "POKEMON": "Nidoran-m",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Poison Point",
        "ABILITIES 2": "Rivalry",
        "HIDDEN ABILITY": "Hustle",
        "EG 1": "Monster",
        "EG 2": "Field",
        "HEALTH POINTS": 55,
        "ATTACK": 47,
        "DEFENSE": 52,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 40,
        "SPEED": 41,
        "TOTAL": 275,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 30,
        "POKEMON": "Nidorina",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Poison Point",
        "ABILITIES 2": "Rivalry",
        "HIDDEN ABILITY": "Hustle",
        "EG 1": "",
        "EG 2": "",
        "HEALTH POINTS": 70,
        "ATTACK": 62,
        "DEFENSE": 67,
        "SPECIAL ATTACK": 55,
        "SPECIAL DEFENSE": 55,
        "SPEED": 56,
        "TOTAL": 365,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 31,
        "POKEMON": "Nidoqueen",
        "TYPE 1": "Poison",
        "TYPE 2": "Ground",
        "ABILITIES 1": "Poison Point",
        "ABILITIES 2": "Rivalry",
        "HIDDEN ABILITY": "Sheer Force",
        "EG 1": "",
        "EG 2": "",
        "HEALTH POINTS": 90,
        "ATTACK": 92,
        "DEFENSE": 87,
        "SPECIAL ATTACK": 75,
        "SPECIAL DEFENSE": 85,
        "SPEED": 76,
        "TOTAL": 505,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 33,
        "POKEMON": "Nidorino",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Poison Point",
        "ABILITIES 2": "Rivalry",
        "HIDDEN ABILITY": "Hustle",
        "EG 1": "Monster",
        "EG 2": "Field",
        "HEALTH POINTS": 61,
        "ATTACK": 72,
        "DEFENSE": 57,
        "SPECIAL ATTACK": 55,
        "SPECIAL DEFENSE": 55,
        "SPEED": 65,
        "TOTAL": 365,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 34,
        "POKEMON": "Nidoking",
        "TYPE 1": "Poison",
        "TYPE 2": "Ground",
        "ABILITIES 1": "Poison Point",
        "ABILITIES 2": "Rivalry",
        "HIDDEN ABILITY": "Sheer Force",
        "EG 1": "Monster",
        "EG 2": "Field",
        "HEALTH POINTS": 81,
        "ATTACK": 102,
        "DEFENSE": 77,
        "SPECIAL ATTACK": 85,
        "SPECIAL DEFENSE": 75,
        "SPEED": 85,
        "TOTAL": 505,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 35,
        "POKEMON": "Clefairy",
        "TYPE 1": "Fairy",
        "TYPE 2": "",
        "ABILITIES 1": "Cute Charm",
        "ABILITIES 2": "Magic Guard",
        "HIDDEN ABILITY": "Friend Guard",
        "EG 1": "Fairy",
        "EG 2": "",
        "HEALTH POINTS": 70,
        "ATTACK": 45,
        "DEFENSE": 48,
        "SPECIAL ATTACK": 60,
        "SPECIAL DEFENSE": 65,
        "SPEED": 35,
        "TOTAL": 323,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 36,
        "POKEMON": "Clefable",
        "TYPE 1": "Fairy",
        "TYPE 2": "",
        "ABILITIES 1": "Cute Charm",
        "ABILITIES 2": "Magic Guard",
        "HIDDEN ABILITY": "Unaware",
        "EG 1": "Fairy",
        "EG 2": "",
        "HEALTH POINTS": 95,
        "ATTACK": 70,
        "DEFENSE": 73,
        "SPECIAL ATTACK": 95,
        "SPECIAL DEFENSE": 90,
        "SPEED": 60,
        "TOTAL": 483,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 37,
        "POKEMON": "Vulpix",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Flash Fire",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Drought",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 38,
        "ATTACK": 41,
        "DEFENSE": 40,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 65,
        "SPEED": 65,
        "TOTAL": 299,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 38,
        "POKEMON": "Ninetales",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Flash Fire",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Drought",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 73,
        "ATTACK": 76,
        "DEFENSE": 75,
        "SPECIAL ATTACK": 81,
        "SPECIAL DEFENSE": 100,
        "SPEED": 100,
        "TOTAL": 505,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 39,
        "POKEMON": "Jigglypuff",
        "TYPE 1": "Normal",
        "TYPE 2": "Fairy",
        "ABILITIES 1": "Cute Charm",
        "ABILITIES 2": "Competitive",
        "HIDDEN ABILITY": "Friend Guard",
        "EG 1": "Fairy",
        "EG 2": "",
        "HEALTH POINTS": 115,
        "ATTACK": 45,
        "DEFENSE": 20,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 25,
        "SPEED": 20,
        "TOTAL": 270,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 40,
        "POKEMON": "Wigglytuff",
        "TYPE 1": "Normal",
        "TYPE 2": "Fairy",
        "ABILITIES 1": "Cute Charm",
        "ABILITIES 2": "Competitive",
        "HIDDEN ABILITY": "Frisk",
        "EG 1": "Fairy",
        "EG 2": "",
        "HEALTH POINTS": 140,
        "ATTACK": 70,
        "DEFENSE": 45,
        "SPECIAL ATTACK": 85,
        "SPECIAL DEFENSE": 50,
        "SPEED": 45,
        "TOTAL": 435,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 41,
        "POKEMON": "Zubat",
        "TYPE 1": "Poison",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Inner Focus",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Infiltrator",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 45,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 30,
        "SPECIAL DEFENSE": 40,
        "SPEED": 55,
        "TOTAL": 245,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 42,
        "POKEMON": "Golbat",
        "TYPE 1": "Poison",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Inner Focus",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Infiltrator",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 75,
        "ATTACK": 80,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 75,
        "SPEED": 90,
        "TOTAL": 455,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 43,
        "POKEMON": "Oddish",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Chlorophyll",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Run Away",
        "EG 1": "Grass",
        "EG 2": "",
        "HEALTH POINTS": 45,
        "ATTACK": 50,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 75,
        "SPECIAL DEFENSE": 65,
        "SPEED": 30,
        "TOTAL": 320,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 44,
        "POKEMON": "Gloom",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Chlorophyll",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Stench",
        "EG 1": "Grass",
        "EG 2": "",
        "HEALTH POINTS": 60,
        "ATTACK": 65,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 85,
        "SPECIAL DEFENSE": 75,
        "SPEED": 40,
        "TOTAL": 395,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 45,
        "POKEMON": "Vileplume",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Chlorophyll",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Effect Spore",
        "EG 1": "Grass",
        "EG 2": "",
        "HEALTH POINTS": 75,
        "ATTACK": 80,
        "DEFENSE": 85,
        "SPECIAL ATTACK": 110,
        "SPECIAL DEFENSE": 90,
        "SPEED": 50,
        "TOTAL": 490,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 46,
        "POKEMON": "Paras",
        "TYPE 1": "Bug",
        "TYPE 2": "Grass",
        "ABILITIES 1": "Effect Spore",
        "ABILITIES 2": "Dry Skin",
        "HIDDEN ABILITY": "Damp",
        "EG 1": "Bug",
        "EG 2": "Grass",
        "HEALTH POINTS": 35,
        "ATTACK": 70,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 55,
        "SPEED": 25,
        "TOTAL": 285,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 47,
        "POKEMON": "Parasect",
        "TYPE 1": "Bug",
        "TYPE 2": "Grass",
        "ABILITIES 1": "Effect Spore",
        "ABILITIES 2": "Dry Skin",
        "HIDDEN ABILITY": "Damp",
        "EG 1": "Bug",
        "EG 2": "Grass",
        "HEALTH POINTS": 60,
        "ATTACK": 95,
        "DEFENSE": 80,
        "SPECIAL ATTACK": 60,
        "SPECIAL DEFENSE": 80,
        "SPEED": 30,
        "TOTAL": 405,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 48,
        "POKEMON": "Venonat",
        "TYPE 1": "Bug",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Compoundeyes",
        "ABILITIES 2": "Tinted Lens",
        "HIDDEN ABILITY": "Run Away",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 60,
        "ATTACK": 55,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 55,
        "SPEED": 45,
        "TOTAL": 305,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 49,
        "POKEMON": "Venomoth",
        "TYPE 1": "Bug",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Shield Dust",
        "ABILITIES 2": "Tinted Lens",
        "HIDDEN ABILITY": "Wonder Skin",
        "EG 1": "Bug",
        "EG 2": "",
        "HEALTH POINTS": 70,
        "ATTACK": 65,
        "DEFENSE": 60,
        "SPECIAL ATTACK": 90,
        "SPECIAL DEFENSE": 75,
        "SPEED": 90,
        "TOTAL": 450,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 50,
        "POKEMON": "Diglett",
        "TYPE 1": "Ground",
        "TYPE 2": "",
        "ABILITIES 1": "Sand Veil",
        "ABILITIES 2": "Arena Trap",
        "HIDDEN ABILITY": "Sand Force",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 10,
        "ATTACK": 55,
        "DEFENSE": 25,
        "SPECIAL ATTACK": 35,
        "SPECIAL DEFENSE": 45,
        "SPEED": 95,
        "TOTAL": 265,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 51,
        "POKEMON": "Dugtrio",
        "TYPE 1": "Ground",
        "TYPE 2": "",
        "ABILITIES 1": "Sand Veil",
        "ABILITIES 2": "Arena Trap",
        "HIDDEN ABILITY": "Sand Force",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 35,
        "ATTACK": 80,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 70,
        "SPEED": 120,
        "TOTAL": 405,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 52,
        "POKEMON": "Meowth",
        "TYPE 1": "Normal",
        "TYPE 2": "",
        "ABILITIES 1": "Pickup",
        "ABILITIES 2": "Technician",
        "HIDDEN ABILITY": "Unnerve",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 45,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 40,
        "SPEED": 90,
        "TOTAL": 290,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 53,
        "POKEMON": "Persian",
        "TYPE 1": "Normal",
        "TYPE 2": "",
        "ABILITIES 1": "Limber",
        "ABILITIES 2": "Technician",
        "HIDDEN ABILITY": "Unnerve",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 70,
        "DEFENSE": 60,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 65,
        "SPEED": 115,
        "TOTAL": 440,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 54,
        "POKEMON": "Psyduck",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Damp",
        "ABILITIES 2": "Cloud Nine",
        "HIDDEN ABILITY": "Swift Swim",
        "EG 1": "Water 1",
        "EG 2": "Field",
        "HEALTH POINTS": 50,
        "ATTACK": 52,
        "DEFENSE": 48,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 50,
        "SPEED": 55,
        "TOTAL": 320,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 55,
        "POKEMON": "Golduck",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Damp",
        "ABILITIES 2": "Cloud Nine",
        "HIDDEN ABILITY": "Swift Swim",
        "EG 1": "Water 1",
        "EG 2": "Field",
        "HEALTH POINTS": 80,
        "ATTACK": 82,
        "DEFENSE": 78,
        "SPECIAL ATTACK": 95,
        "SPECIAL DEFENSE": 80,
        "SPEED": 85,
        "TOTAL": 500,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 56,
        "POKEMON": "Mankey",
        "TYPE 1": "Fighting",
        "TYPE 2": "",
        "ABILITIES 1": "Vital Spirit",
        "ABILITIES 2": "Anger Point",
        "HIDDEN ABILITY": "Defiant",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 80,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 35,
        "SPECIAL DEFENSE": 45,
        "SPEED": 70,
        "TOTAL": 305,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 57,
        "POKEMON": "Primeape",
        "TYPE 1": "Fighting",
        "TYPE 2": "",
        "ABILITIES 1": "Vital Spirit",
        "ABILITIES 2": "Anger Point",
        "HIDDEN ABILITY": "Defiant",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 105,
        "DEFENSE": 60,
        "SPECIAL ATTACK": 60,
        "SPECIAL DEFENSE": 70,
        "SPEED": 95,
        "TOTAL": 455,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 58,
        "POKEMON": "Growlithe",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Intimidate",
        "ABILITIES 2": "Flash Fire",
        "HIDDEN ABILITY": "Justified",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 55,
        "ATTACK": 70,
        "DEFENSE": 45,
        "SPECIAL ATTACK": 70,
        "SPECIAL DEFENSE": 50,
        "SPEED": 60,
        "TOTAL": 350,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 59,
        "POKEMON": "Arcanine",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Intimidate",
        "ABILITIES 2": "Flash Fire",
        "HIDDEN ABILITY": "Justified",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 90,
        "ATTACK": 110,
        "DEFENSE": 80,
        "SPECIAL ATTACK": 100,
        "SPECIAL DEFENSE": 80,
        "SPEED": 95,
        "TOTAL": 555,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 60,
        "POKEMON": "Poliwag",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Water Absorb",
        "ABILITIES 2": "Damp",
        "HIDDEN ABILITY": "Swift Swim",
        "EG 1": "Water 1",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 50,
        "DEFENSE": 40,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 40,
        "SPEED": 90,
        "TOTAL": 300,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 61,
        "POKEMON": "Poliwhirl",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Water Absorb",
        "ABILITIES 2": "Damp",
        "HIDDEN ABILITY": "Swift Swim",
        "EG 1": "Water 1",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 65,
        "DEFENSE": 65,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 50,
        "SPEED": 90,
        "TOTAL": 385,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 62,
        "POKEMON": "Poliwrath",
        "TYPE 1": "Water",
        "TYPE 2": "Fighting",
        "ABILITIES 1": "Water Absorb",
        "ABILITIES 2": "Damp",
        "HIDDEN ABILITY": "Swift Swim",
        "EG 1": "Water 1",
        "EG 2": "",
        "HEALTH POINTS": 90,
        "ATTACK": 95,
        "DEFENSE": 95,
        "SPECIAL ATTACK": 70,
        "SPECIAL DEFENSE": 90,
        "SPEED": 70,
        "TOTAL": 510,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 63,
        "POKEMON": "Abra",
        "TYPE 1": "Psychic",
        "TYPE 2": "",
        "ABILITIES 1": "Synchronize",
        "ABILITIES 2": "Inner Focus",
        "HIDDEN ABILITY": "Magic Guard",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 25,
        "ATTACK": 20,
        "DEFENSE": 15,
        "SPECIAL ATTACK": 105,
        "SPECIAL DEFENSE": 55,
        "SPEED": 90,
        "TOTAL": 310,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 64,
        "POKEMON": "Kadabra",
        "TYPE 1": "Psychic",
        "TYPE 2": "",
        "ABILITIES 1": "Synchronize",
        "ABILITIES 2": "Inner Focus",
        "HIDDEN ABILITY": "Magic Guard",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 35,
        "DEFENSE": 30,
        "SPECIAL ATTACK": 120,
        "SPECIAL DEFENSE": 70,
        "SPEED": 105,
        "TOTAL": 400,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 65,
        "POKEMON": "Alakazam",
        "TYPE 1": "Psychic",
        "TYPE 2": "",
        "ABILITIES 1": "Synchronize",
        "ABILITIES 2": "Inner Focus",
        "HIDDEN ABILITY": "Magic Guard",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 55,
        "ATTACK": 50,
        "DEFENSE": 45,
        "SPECIAL ATTACK": 135,
        "SPECIAL DEFENSE": 95,
        "SPEED": 120,
        "TOTAL": 500,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 66,
        "POKEMON": "Machop",
        "TYPE 1": "Fighting",
        "TYPE 2": "",
        "ABILITIES 1": "Guts",
        "ABILITIES 2": "No Guard",
        "HIDDEN ABILITY": "Steadfast",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 70,
        "ATTACK": 80,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 35,
        "SPECIAL DEFENSE": 35,
        "SPEED": 35,
        "TOTAL": 305,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 67,
        "POKEMON": "Machoke",
        "TYPE 1": "Fighting",
        "TYPE 2": "",
        "ABILITIES 1": "Guts",
        "ABILITIES 2": "No Guard",
        "HIDDEN ABILITY": "Steadfast",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 80,
        "ATTACK": 100,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 60,
        "SPEED": 45,
        "TOTAL": 405,
        "HATCH STEPS": 3840
    },
    {
        "DEX": 68,
        "POKEMON": "Machamp",
        "TYPE 1": "Fighting",
        "TYPE 2": "",
        "ABILITIES 1": "Guts",
        "ABILITIES 2": "No Guard",
        "HIDDEN ABILITY": "Steadfast",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 90,
        "ATTACK": 130,
        "DEFENSE": 80,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 85,
        "SPEED": 55,
        "TOTAL": 505,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 69,
        "POKEMON": "Bellsprout",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Chlorophyll",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Gluttony",
        "EG 1": "Grass",
        "EG 2": "",
        "HEALTH POINTS": 50,
        "ATTACK": 75,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 70,
        "SPECIAL DEFENSE": 30,
        "SPEED": 40,
        "TOTAL": 300,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 70,
        "POKEMON": "Weepinbell",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Chlorophyll",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Gluttony",
        "EG 1": "Grass",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 90,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 85,
        "SPECIAL DEFENSE": 45,
        "SPEED": 55,
        "TOTAL": 390,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 71,
        "POKEMON": "Victreebel",
        "TYPE 1": "Grass",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Chlorophyll",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "Gluttony",
        "EG 1": "Grass",
        "EG 2": "",
        "HEALTH POINTS": 80,
        "ATTACK": 105,
        "DEFENSE": 65,
        "SPECIAL ATTACK": 100,
        "SPECIAL DEFENSE": 70,
        "SPEED": 70,
        "TOTAL": 490,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 72,
        "POKEMON": "Tentacool",
        "TYPE 1": "Water",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Clear Body",
        "ABILITIES 2": "Liquid Ooze",
        "HIDDEN ABILITY": "Rain Dish",
        "EG 1": "Water 3",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 40,
        "DEFENSE": 35,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 100,
        "SPEED": 70,
        "TOTAL": 335,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 73,
        "POKEMON": "Tentacruel",
        "TYPE 1": "Water",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Clear Body",
        "ABILITIES 2": "Liquid Ooze",
        "HIDDEN ABILITY": "Rain Dish",
        "EG 1": "Water 3",
        "EG 2": "",
        "HEALTH POINTS": 80,
        "ATTACK": 70,
        "DEFENSE": 65,
        "SPECIAL ATTACK": 80,
        "SPECIAL DEFENSE": 120,
        "SPEED": 100,
        "TOTAL": 515,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 74,
        "POKEMON": "Geodude",
        "TYPE 1": "Rock",
        "TYPE 2": "Ground",
        "ABILITIES 1": "Rock Head",
        "ABILITIES 2": "Sturdy",
        "HIDDEN ABILITY": "Sand Veil",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 80,
        "DEFENSE": 100,
        "SPECIAL ATTACK": 30,
        "SPECIAL DEFENSE": 30,
        "SPEED": 20,
        "TOTAL": 300,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 75,
        "POKEMON": "Graveler",
        "TYPE 1": "Rock",
        "TYPE 2": "Ground",
        "ABILITIES 1": "Rock Head",
        "ABILITIES 2": "Sturdy",
        "HIDDEN ABILITY": "Sand Veil",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 55,
        "ATTACK": 95,
        "DEFENSE": 115,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 45,
        "SPEED": 35,
        "TOTAL": 390,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 76,
        "POKEMON": "Golem",
        "TYPE 1": "Rock",
        "TYPE 2": "Ground",
        "ABILITIES 1": "Rock Head",
        "ABILITIES 2": "Sturdy",
        "HIDDEN ABILITY": "Sand Veil",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 80,
        "ATTACK": 120,
        "DEFENSE": 130,
        "SPECIAL ATTACK": 55,
        "SPECIAL DEFENSE": 65,
        "SPEED": 45,
        "TOTAL": 495,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 77,
        "POKEMON": "Ponyta",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Run Away",
        "ABILITIES 2": "Flash Fire",
        "HIDDEN ABILITY": "Flame Body",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 50,
        "ATTACK": 85,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 65,
        "SPEED": 90,
        "TOTAL": 410,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 78,
        "POKEMON": "Rapidash",
        "TYPE 1": "Fire",
        "TYPE 2": "",
        "ABILITIES 1": "Run Away",
        "ABILITIES 2": "Flash Fire",
        "HIDDEN ABILITY": "Flame Body",
        "EG 1": "Field",
        "EG 2": "",
        "HEALTH POINTS": 65,
        "ATTACK": 100,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 80,
        "SPECIAL DEFENSE": 80,
        "SPEED": 105,
        "TOTAL": 500,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 79,
        "POKEMON": "Slowpoke",
        "TYPE 1": "Water",
        "TYPE 2": "Psychic",
        "ABILITIES 1": "Oblivious",
        "ABILITIES 2": "Own Tempo",
        "HIDDEN ABILITY": "Regenerator",
        "EG 1": "Monster",
        "EG 2": "Water 1",
        "HEALTH POINTS": 90,
        "ATTACK": 65,
        "DEFENSE": 65,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 40,
        "SPEED": 15,
        "TOTAL": 315,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 80,
        "POKEMON": "Slowbro",
        "TYPE 1": "Water",
        "TYPE 2": "Psychic",
        "ABILITIES 1": "Oblivious",
        "ABILITIES 2": "Own Tempo",
        "HIDDEN ABILITY": "Regenerator",
        "EG 1": "Monster",
        "EG 2": "Water 1",
        "HEALTH POINTS": 95,
        "ATTACK": 75,
        "DEFENSE": 110,
        "SPECIAL ATTACK": 100,
        "SPECIAL DEFENSE": 80,
        "SPEED": 30,
        "TOTAL": 490,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 81,
        "POKEMON": "Magnemite",
        "TYPE 1": "Electric",
        "TYPE 2": "Steel",
        "ABILITIES 1": "Magnet Pull",
        "ABILITIES 2": "Sturdy",
        "HIDDEN ABILITY": "Analytic",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 25,
        "ATTACK": 35,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 95,
        "SPECIAL DEFENSE": 55,
        "SPEED": 45,
        "TOTAL": 325,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 82,
        "POKEMON": "Magneton",
        "TYPE 1": "Electric",
        "TYPE 2": "Steel",
        "ABILITIES 1": "Magnet Pull",
        "ABILITIES 2": "Sturdy",
        "HIDDEN ABILITY": "Analytic",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 50,
        "ATTACK": 60,
        "DEFENSE": 95,
        "SPECIAL ATTACK": 120,
        "SPECIAL DEFENSE": 70,
        "SPEED": 70,
        "TOTAL": 465,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 83,
        "POKEMON": "Farfetchd",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Keen Eye",
        "ABILITIES 2": "Inner Focus",
        "HIDDEN ABILITY": "Defiant",
        "EG 1": "Flying",
        "EG 2": "Field",
        "HEALTH POINTS": 52,
        "ATTACK": 65,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 58,
        "SPECIAL DEFENSE": 62,
        "SPEED": 60,
        "TOTAL": 352,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 84,
        "POKEMON": "Doduo",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Run Away",
        "ABILITIES 2": "Early Bird",
        "HIDDEN ABILITY": "Tangled Feet",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 35,
        "ATTACK": 85,
        "DEFENSE": 45,
        "SPECIAL ATTACK": 35,
        "SPECIAL DEFENSE": 35,
        "SPEED": 75,
        "TOTAL": 310,
        "HATCH STEPS": 6400
    },
    {
        "DEX": 85,
        "POKEMON": "Dodrio",
        "TYPE 1": "Normal",
        "TYPE 2": "Flying",
        "ABILITIES 1": "Run Away",
        "ABILITIES 2": "Early Bird",
        "HIDDEN ABILITY": "Tangled Feet",
        "EG 1": "Flying",
        "EG 2": "",
        "HEALTH POINTS": 60,
        "ATTACK": 110,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 60,
        "SPECIAL DEFENSE": 60,
        "SPEED": 100,
        "TOTAL": 460,
        "HATCH STEPS": 6400
    },
    {
        "DEX": 86,
        "POKEMON": "Seel",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Thick Fat",
        "ABILITIES 2": "Hydration",
        "HIDDEN ABILITY": "Ice Body",
        "EG 1": "Water 1",
        "EG 2": "Field",
        "HEALTH POINTS": 65,
        "ATTACK": 45,
        "DEFENSE": 55,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 70,
        "SPEED": 45,
        "TOTAL": 325,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 87,
        "POKEMON": "Dewgong",
        "TYPE 1": "Water",
        "TYPE 2": "Ice",
        "ABILITIES 1": "Thick Fat",
        "ABILITIES 2": "Hydration",
        "HIDDEN ABILITY": "Ice Body",
        "EG 1": "Water 1",
        "EG 2": "Field",
        "HEALTH POINTS": 90,
        "ATTACK": 70,
        "DEFENSE": 80,
        "SPECIAL ATTACK": 70,
        "SPECIAL DEFENSE": 95,
        "SPEED": 70,
        "TOTAL": 475,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 88,
        "POKEMON": "Grimer",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Stench",
        "ABILITIES 2": "Sticky Hold",
        "HIDDEN ABILITY": "Poison Touch",
        "EG 1": "Amorphous",
        "EG 2": "",
        "HEALTH POINTS": 80,
        "ATTACK": 80,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 40,
        "SPECIAL DEFENSE": 50,
        "SPEED": 25,
        "TOTAL": 325,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 89,
        "POKEMON": "Muk",
        "TYPE 1": "Poison",
        "TYPE 2": "",
        "ABILITIES 1": "Stench",
        "ABILITIES 2": "Sticky Hold",
        "HIDDEN ABILITY": "Poison Touch",
        "EG 1": "Amorphous",
        "EG 2": "",
        "HEALTH POINTS": 105,
        "ATTACK": 105,
        "DEFENSE": 75,
        "SPECIAL ATTACK": 65,
        "SPECIAL DEFENSE": 100,
        "SPEED": 50,
        "TOTAL": 500,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 90,
        "POKEMON": "Shellder",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Shell Armor",
        "ABILITIES 2": "Skill Link",
        "HIDDEN ABILITY": "Overcoat",
        "EG 1": "Water 3",
        "EG 2": "",
        "HEALTH POINTS": 30,
        "ATTACK": 65,
        "DEFENSE": 100,
        "SPECIAL ATTACK": 45,
        "SPECIAL DEFENSE": 25,
        "SPEED": 40,
        "TOTAL": 305,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 91,
        "POKEMON": "Cloyster",
        "TYPE 1": "Water",
        "TYPE 2": "Ice",
        "ABILITIES 1": "Shell Armor",
        "ABILITIES 2": "Skill Link",
        "HIDDEN ABILITY": "Overcoat",
        "EG 1": "Water 3",
        "EG 2": "",
        "HEALTH POINTS": 50,
        "ATTACK": 95,
        "DEFENSE": 180,
        "SPECIAL ATTACK": 85,
        "SPECIAL DEFENSE": 45,
        "SPEED": 70,
        "TOTAL": 525,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 92,
        "POKEMON": "Gastly",
        "TYPE 1": "Ghost",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Levitate",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "",
        "EG 1": "Amorphous",
        "EG 2": "",
        "HEALTH POINTS": 30,
        "ATTACK": 35,
        "DEFENSE": 30,
        "SPECIAL ATTACK": 100,
        "SPECIAL DEFENSE": 35,
        "SPEED": 80,
        "TOTAL": 310,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 93,
        "POKEMON": "Haunter",
        "TYPE 1": "Ghost",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Levitate",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "",
        "EG 1": "Amorphous",
        "EG 2": "",
        "HEALTH POINTS": 45,
        "ATTACK": 50,
        "DEFENSE": 45,
        "SPECIAL ATTACK": 115,
        "SPECIAL DEFENSE": 55,
        "SPEED": 95,
        "TOTAL": 405,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 94,
        "POKEMON": "Gengar",
        "TYPE 1": "Ghost",
        "TYPE 2": "Poison",
        "ABILITIES 1": "Levitate",
        "ABILITIES 2": "",
        "HIDDEN ABILITY": "",
        "EG 1": "Amorphous",
        "EG 2": "",
        "HEALTH POINTS": 60,
        "ATTACK": 65,
        "DEFENSE": 60,
        "SPECIAL ATTACK": 130,
        "SPECIAL DEFENSE": 75,
        "SPEED": 110,
        "TOTAL": 500,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 95,
        "POKEMON": "Onix",
        "TYPE 1": "Rock",
        "TYPE 2": "Ground",
        "ABILITIES 1": "Rock Head",
        "ABILITIES 2": "Sturdy",
        "HIDDEN ABILITY": "Weak Armor",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 35,
        "ATTACK": 45,
        "DEFENSE": 160,
        "SPECIAL ATTACK": 30,
        "SPECIAL DEFENSE": 45,
        "SPEED": 70,
        "TOTAL": 385,
        "HATCH STEPS": 6400
    },
    {
        "DEX": 96,
        "POKEMON": "Drowzee",
        "TYPE 1": "Psychic",
        "TYPE 2": "",
        "ABILITIES 1": "Insomnia",
        "ABILITIES 2": "Forewarn",
        "HIDDEN ABILITY": "Inner Focus",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 60,
        "ATTACK": 48,
        "DEFENSE": 45,
        "SPECIAL ATTACK": 43,
        "SPECIAL DEFENSE": 90,
        "SPEED": 42,
        "TOTAL": 328,
        "HATCH STEPS": 6400
    },
    {
        "DEX": 97,
        "POKEMON": "Hypno",
        "TYPE 1": "Psychic",
        "TYPE 2": "",
        "ABILITIES 1": "Insomnia",
        "ABILITIES 2": "Forewarn",
        "HIDDEN ABILITY": "Inner Focus",
        "EG 1": "Human-Like",
        "EG 2": "",
        "HEALTH POINTS": 85,
        "ATTACK": 73,
        "DEFENSE": 70,
        "SPECIAL ATTACK": 73,
        "SPECIAL DEFENSE": 115,
        "SPEED": 67,
        "TOTAL": 483,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 98,
        "POKEMON": "Krabby",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Hyper Cutter",
        "ABILITIES 2": "Shell Armor",
        "HIDDEN ABILITY": "Sheer Force",
        "EG 1": "Water 3",
        "EG 2": "",
        "HEALTH POINTS": 30,
        "ATTACK": 105,
        "DEFENSE": 90,
        "SPECIAL ATTACK": 25,
        "SPECIAL DEFENSE": 25,
        "SPEED": 50,
        "TOTAL": 325,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 99,
        "POKEMON": "Kingler",
        "TYPE 1": "Water",
        "TYPE 2": "",
        "ABILITIES 1": "Hyper Cutter",
        "ABILITIES 2": "Shell Armor",
        "HIDDEN ABILITY": "Sheer Force",
        "EG 1": "Water 3",
        "EG 2": "",
        "HEALTH POINTS": 55,
        "ATTACK": 130,
        "DEFENSE": 115,
        "SPECIAL ATTACK": 50,
        "SPECIAL DEFENSE": 50,
        "SPEED": 75,
        "TOTAL": 475,
        "HATCH STEPS": 5120
    },
    {
        "DEX": 100,
        "POKEMON": "Voltorb",
        "TYPE 1": "Electric",
        "TYPE 2": "",
        "ABILITIES 1": "Soundproof",
        "ABILITIES 2": "Static",
        "HIDDEN ABILITY": "Aftermath",
        "EG 1": "Mineral",
        "EG 2": "",
        "HEALTH POINTS": 40,
        "ATTACK": 30,
        "DEFENSE": 50,
        "SPECIAL ATTACK": 55,
        "SPECIAL DEFENSE": 55,
        "SPEED": 100,
        "TOTAL": 330,
        "HATCH STEPS": 5120
    }];